title: "Training Schedule"
description: SNP-Seek version 3 and RicePilaf Training Workshop
theme: jekyll-theme-cayman

# Add custom CSS
plugins:
  - jekyll-include-cache

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "/assets/style.css"
